preparing code style for real changes

diff --git a/packer b/packer
--- a/packer
+++ b/packer
@@ -2,11 +2,12 @@
 # Copyright Matthew Bruenig <matthewbruenig@gmail.com>
 # Licensed under GPL version 3
 
-tmpfile="/tmp/packeroutput-$UID"
-makepkgconf="/etc/makepkg.conf"
-pacmanconf="/etc/pacman.conf"
-pacman="$(type -p pacman)"
-outputpacman="$(type -p pacman-color)"
+# TODO: mktemp
+tmpfile=/tmp/packeroutput-$UID
+makepkgconf=/etc/makepkg.conf
+pacmanconf=/etc/pacman.conf
+pacman=$(type -p pacman)
+outputpacman=$(type -p pacman-color)
 if [[ $outputpacman ]]; then
   COLOR1='\e[1;39m'
   COLOR2='\e[1;32m'
@@ -16,7 +17,7 @@ if [[ $outputpacman ]]; then
   COLOR6='\e[1;33m'
   ENDCOLOR='\e[0m'
 else
-  outputpacman="$pacman"
+  outputpacman=$pacman
 fi
 
 err() {
@@ -25,24 +26,24 @@ err() {
 }
 
 usage() {
-  echo "usage: packer [option] [package] [package] [...]"
+  echo 'usage: packer [option] [package] [package] [...]'
   echo
-  echo "    -S          - installs package"
-  echo "    -Syu|-Su    - updates all packages"
-  echo "    -Ss         - searches for package"
-  echo "    -Si         - outputs info for package"
+  echo '    -S          - installs package'
+  echo '    -Syu|-Su    - updates all packages'
+  echo '    -Ss         - searches for package'
+  echo '    -Si         - outputs info for package'
   echo
-  echo "    --noconfirm - do not prompt for confirmation"
-  echo "    --auronly   - only do actions for aur"
-  echo "    --devel     - update devel packages during -Su"
-  echo "    --skipinteg - when using makepkg, do not check md5s"
-  echo "    -h          - outputs this message"
+  echo '    --noconfirm - do not prompt for confirmation'
+  echo '    --auronly   - only do actions for aur'
+  echo '    --devel     - update devel packages during -Su'
+  echo '    --skipinteg - when using makepkg, do not check md5s'
+  echo '    -h          - outputs this message'
   exit
 }
 
 # Called whenever anything needs to be run as root ($@ is the command)
 runasroot() {
-  if [[ $UID -eq 0 ]]; then
+  if (( UID == 0 )); then
     "$@"
   elif sudo -l "$@" &>/dev/null; then
     sudo "$@"
@@ -60,8 +61,7 @@ sourcemakepkgconf() {
 
 # Parse IgnorePkg from pacman.conf, put in globally accessible ignoredpackages array
 getignoredpackages() {
-  IFS=$'\n'
-  IFS="$IFS "
+  IFS=$'\n'" "
   ignoredpackages=( $(grep '^IgnorePkg' "$pacmanconf" | cut -d '=' -f 2) )
 }
 
@@ -94,7 +94,7 @@ existsinlocal() {
 # Scrapes the aur deps from PKGBUILDS and puts in globally available dependencies array
 scrapeaurdeps() {
   wget -q "http://aur.archlinux.org/packages/$1/$1/PKGBUILD" -O "$tmpfile"
-  [[ $? -ne 0 ]] && err "Package \`$1' does not exist."
+  (( $? != 0 )) && err "Package \`$1' does not exist."
   . "$tmpfile"
   IFS=$'\n'
   dependencies=( $(echo -e "${depends[*]}\n${makedepends[*]}" | sed -e 's/=.*//' -e 's/>.*//' -e 's/<.*//'| sort -u) )
@@ -114,7 +114,7 @@ finddeps() {
     elif existsinaur "$dep"; then
       aurdeps+=("$dep")
     else
-      [[ $option = "install" ]] &&  err "Dependency \`$dep' of \`$1' does not exist."
+      [[ $option == "install" ]] &&  err "Dependency \`$dep' of \`$1' does not exist."
       echo "Dependency \`$dep of \`$1' does not exist."
       return 1
     fi
@@ -144,6 +144,7 @@ finddeps() {
       done
     done
   fi
+  # Jesus christ
 }
 
 # Displays a progress bar ($1 is numerator, $2 is denominator)
@@ -181,7 +182,7 @@ aurversionisnewer() {
   unset aurversion
   if ! grep -Fq ':"No result found"' "$tmpfile"; then
     aurversion="$(cut -d '"' -f 18 "$tmpfile")"
-    if [[ "$(vercmp "$aurversion" "$2")" -gt 0  ]]; then
+    if (( $(vercmp "$aurversion" "$2") > 0  )); then
       return 0
     else
       return 1
@@ -216,8 +217,7 @@ aurinstall() {
       echo
       case "$answer" in
         'Y'|'y'|'')
-          [[ $EDITOR ]] || EDITOR=vi
-          $EDITOR PKGBUILD
+          ${EDITOR:-vi} PKGBUILD
           ;;
       esac
     fi
@@ -235,25 +235,24 @@ aurinstall() {
       echo
       case "$answer" in
         'Y'|'y'|'')
-          [[ $EDITOR ]] || EDITOR=vi
-          $EDITOR "$install"
+          ${EDITOR:-vi} "$install"
           ;;
       esac 
     fi
   fi
 
   # Installation (makepkg and pacman)
-  if [[ $UID -eq 0 ]]; then
+  if (( UID == 0 )); then
     makepkg $MAKEPKGOPTS --asroot -f
   else
     makepkg $MAKEPKGOPTS -f
   fi
 
-  [[ $? -ne 0 ]] && echo "The build failed." && return 1
-  if  [[ $2 = dependency ]]; then
-    runasroot $outputpacman --asdeps -U $pkgname-*.pkg.tar.gz
-  elif [[ $2 = explicit ]]; then
-    runasroot $outputpacman -U $pkgname-*.pkg.tar.gz
+  (( $? != 0 )) && { echo "The build failed."; return 1; }
+  if  [[ $2 == dependency ]]; then
+    runasroot $outputpacman --asdeps -U $pkgname-$pkgver-*.pkg.tar.gz
+  elif [[ $2 == explicit ]]; then
+    runasroot $outputpacman -U $pkgname-$pkgver-*.pkg.tar.gz
   fi
 }
 
@@ -415,13 +414,13 @@ done
 [[ $option != "update" && -z $packageargs ]] && err "Must specify a package."
 
 # Install (-S) handling
-if [[ $option = install ]]; then
+if [[ $option == install ]]; then
   installhandling "${packageargs[@]}"
   exit
 fi
 
 # Update (-Su) handling
-if [[ $option = update ]]; then
+if [[ $option == update ]]; then
   getignoredpackages
   # Pacman update
   if ! [[ $auronly ]]; then
@@ -442,27 +441,27 @@ if [[ $option = update ]]; then
   if [[ $devel ]]; then
     for ((i=0; i<$total; i++)); do 
       aurbar "$((i+1))" "$total"
-      if isignored "${packages[$i]%% *}"; then
-        checkignores+=("${packages[$i]}")
+      if isignored "${packages[i]%% *}"; then
+        checkignores+=("${packages[i]}")
       else
         unset _darcstrunk _cvsroot _gitroot _svntrunk _bzrtrunk _hgroot
-        wget -q "http://aur.archlinux.org/packages/${packages[$i]%% *}/${packages[$i]%% *}/PKGBUILD" -O "$tmpfile"
-        [[ $? -eq 0 ]] || continue
+        wget -q "http://aur.archlinux.org/packages/${packages[i]%% *}/${packages[i]%% *}/PKGBUILD" -O "$tmpfile"
+        (( $? == 0 )) || continue
         . "$tmpfile"
-        if [[ "$(vercmp "$pkgver" "${packages[$i]##* }")" -gt 0 ]]; then
-          newpackages+=("${packages[$i]%% *}")
+        if (( "$(vercmp "$pkgver" "${packages[i]##* }")" > 0 )); then
+          newpackages+=("${packages[i]%% *}")
         elif [[ ${_darcstrunk} || ${_cvsroot} || ${_gitroot} || ${_svntrunk} || ${_bzrtrunk} || ${_hgroot} ]]; then 
-          newpackages+=("${packages[$i]%% *}")
+          newpackages+=("${packages[i]%% *}")
         fi
       fi
     done
   else
     for ((i=0; i<$total; i++)); do 
       aurbar "$((i+1))" "$total"
-      if isignored "${packages[$i]%% *}"; then
-        checkignores+=("${packages[$i]}")
-      elif aurversionisnewer "${packages[$i]%% *}" "${packages[$i]##* }"; then
-        newpackages+=("${packages[$i]%% *}")
+      if isignored "${packages[i]%% *}"; then
+        checkignores+=("${packages[i]}")
+      elif aurversionisnewer "${packages[i]%% *}" "${packages[i]##* }"; then
+        newpackages+=("${packages[i]%% *}")
     fi
     done
   fi
@@ -537,10 +536,10 @@ if [[ $option = update ]]; then
 fi
 
 # Search (-Ss) handling
-if [[ $option = search || $option = searchinstall ]]; then
+if [[ $option == search || $option == searchinstall ]]; then
   # Pacman searching 
   if ! [[ $auronly ]]; then
-    if [[ $option = search ]]; then
+    if [[ $option == search ]]; then
       $outputpacman -Ss -- "${packageargs[@]}"
     else
       # Get the pacman output into various arrays and output
@@ -562,7 +561,7 @@ if [[ $option = search || $option = searchinstall ]]; then
   fi
 
   # Aur searching and tmpfile preparation
-  if  [[ ${#packageargs[@]} -eq 1 ]]; then
+  if  (( ${#packageargs[@]} == 1 )); then
     # Fill up the arrays with package information from dump file
     wget -q "http://aur.archlinux.org/rpc.php?type=search&arg=$packageargs" -O- | sed -e 's/","/"\n"/g' -e 's/\\//g' > "$tmpfile" 
     parsefile="$tmpfile"
@@ -583,7 +582,7 @@ if [[ $option = search || $option = searchinstall ]]; then
   aurtotal="${#aurname[@]}"
 
   # Echo out the -Ss formatted package information
-  if [[ $option = search ]]; then
+  if [[ $option == search ]]; then
     for ((i=0 ; i<$aurtotal ; i++)); do
       echo -e "${COLOR3}aur/${COLOR1}${aurname[$i]} ${COLOR2}${version[$i]}${ENDCOLOR}\n    ${description[$i]}"
     done
@@ -596,7 +595,7 @@ if [[ $option = search || $option = searchinstall ]]; then
   fi
 
   # Prompt and install selected numbers
-  if [[ $option = searchinstall ]]; then
+  if [[ $option == searchinstall ]]; then
     pkglist=()
     allpackages=( "${pacname[@]}" "${aurname[@]}" )
 
@@ -610,7 +609,7 @@ if [[ $option = search || $option = searchinstall ]]; then
     if [[ $REPLY ]]; then
       IFS=' '
       for num in $REPLY; do
-        if [[ $num -lt $alltotal ]]; then
+        if (( $num < $alltotal )); then
           pkglist+=("${allpackages[$num]}")
         else
           err "Number \`$num' is not assigned to any of the packages."
@@ -628,7 +627,7 @@ if [[ $option = search || $option = searchinstall ]]; then
 fi
 
 # Info (-Si) handling
-if [[ $option = info ]]; then
+if [[ $option == info ]]; then
   # Pacman info check
   sourcemakepkgconf
   for package in "${packageargs[@]}"; do
@@ -637,7 +636,7 @@ if [[ $option = info ]]; then
       exit
     else # Check to see if it is in the aur
       wget -q "http://aur.archlinux.org/packages/$package/$package/PKGBUILD" -O "$tmpfile"
-      [[ $? -eq 0 ]] || err "No result found."
+      (( $? == 0 )) || err "No result found."
       . "$tmpfile"
 
       # Echo out the -Si formatted package information
@@ -656,22 +655,22 @@ if [[ $option = info ]]; then
 
       echo -e -n "${COLOR1}Optional Deps  : ${ENDCOLOR}"
       len="${#optdepends[@]}"
-      if [[ $len -eq 0 ]]; then
+      if (( len == 0 )); then
         echo "None"
       else
         for ((i=0 ; i<$len ; i++)); do
-          if [[ $i = 0 ]]; then
-            echo "${optdepends[$i]}"
+          if (( i == 0 )); then
+            echo "${optdepends[i]}"
           else
-            echo -e "                 ${optdepends[$i]}" 
+            echo -e "                 ${optdepends[i]}" 
           fi
         done
       fi
 
-      [[ -z "${conflicts}" ]] && conflicts="None"
+      [[ -z $conflicts ]] && conflicts="None"
       echo -e "${COLOR1}Conflicts With : ${ENDCOLOR}${conflicts[*]}"
 
-      [[ -z "${replaces}" ]] && replaces="None"
+      [[ -z $replaces ]] && replaces="None"
       echo -e "${COLOR1}Replaces       : ${ENDCOLOR}${replaces[*]}"
       echo -e "${COLOR1}Architecture   : ${ENDCOLOR}${arch[*]}"
       echo -e "${COLOR1}Description    : ${ENDCOLOR}$pkgdesc"
